import { useEffect, useState } from "react";
import { Activity, Archive, BarChart3, BookOpenCheck, BriefcaseBusiness, ClipboardCheck, FileCheck2, FilePlus2, Gavel, HandCoins, LayoutDashboard, PackageCheck, Scale, Settings, ShieldCheck, Store, Users, WalletCards } from "lucide-react";
import type { Mode } from "../types/procura";
import { LIVE_CHAIN_ID, LIVE_CONTRACT, LIVE_NETWORK } from "../lib/liveConfig";
import { StatusBadge } from "./StatusBadge";

export type RouteKey = "command-center" | "tenders" | "tender-builder" | "tender-room" | "supplier-portal" | "bid-builder" | "evaluation-room" | "award-desk" | "delivery-workspace" | "inspection-room" | "payments" | "disputes" | "suppliers" | "analytics" | "proof-audit" | "settings";

const groups = [
  { label: "Operate", items: [{ key: "command-center", label: "Command Center", icon: LayoutDashboard }, { key: "tenders", label: "Tenders", icon: BriefcaseBusiness }, { key: "tender-builder", label: "Tender Builder", icon: FilePlus2 }, { key: "tender-room", label: "Tender Room", icon: Archive }] },
  { label: "Evaluate", items: [{ key: "supplier-portal", label: "Supplier Portal", icon: Store }, { key: "bid-builder", label: "Bid Builder", icon: ClipboardCheck }, { key: "evaluation-room", label: "Evaluation Room", icon: Gavel }, { key: "award-desk", label: "Award Desk", icon: FileCheck2 }] },
  { label: "Fulfil", items: [{ key: "delivery-workspace", label: "Delivery Workspace", icon: PackageCheck }, { key: "inspection-room", label: "Inspection Room", icon: ShieldCheck }, { key: "payments", label: "Payments & Escrow", icon: WalletCards }, { key: "disputes", label: "Disputes", icon: Scale }] },
  { label: "Observe", items: [{ key: "suppliers", label: "Suppliers", icon: Users }, { key: "analytics", label: "Analytics", icon: BarChart3 }, { key: "proof-audit", label: "Proof & Audit", icon: BookOpenCheck }, { key: "settings", label: "Settings", icon: Settings }] }
] as const;

export function routeFromPath(pathname: string): RouteKey { const value = pathname.replace(/^\//, "") as RouteKey; return groups.some((group) => group.items.some((item) => item.key === value)) ? value : "command-center"; }

export function Shell({ route, mode, onNavigate, children }: { route: RouteKey; mode: Mode; onNavigate: (route: RouteKey) => void; children: React.ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { setMobileOpen(false); }, [route]);
  return <div data-live-contract={LIVE_CONTRACT} className="min-h-screen bg-paper text-ink"><aside className={`fixed inset-y-0 left-0 z-30 w-[252px] overflow-y-auto border-r border-line bg-[#f9faf7] px-4 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="flex items-center gap-3 px-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-moss text-white"><Activity size={18} /></div><div><div className="text-lg font-semibold tracking-[-.03em]">Procura</div><div className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">Trust layer</div></div></div><div className="mt-8 space-y-6">{groups.map((group) => <div key={group.label}><div className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">{group.label}</div><nav className="space-y-0.5">{group.items.map((item) => { const Icon = item.icon; const active = route === item.key; return <button key={item.key} onClick={() => onNavigate(item.key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${active ? "bg-[#e3eee8] font-semibold text-moss" : "text-slate-600 hover:bg-white hover:text-ink"}`}><Icon size={16} strokeWidth={active ? 2.4 : 1.8} />{item.label}{active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-moss" />}</button>; })}</nav></div>)}</div><div className="mt-6 rounded-xl border border-line bg-white p-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold">Network</span><span className="h-2 w-2 rounded-full bg-amber" /></div><div className="mt-1 text-xs text-slate-500">{LIVE_NETWORK} · chain {LIVE_CHAIN_ID} · wallet gated</div></div></aside><main className="lg:pl-[252px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-line bg-paper/90 px-5 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-lg border border-line bg-white p-2 lg:hidden" onClick={() => setMobileOpen(true)}><BriefcaseBusiness size={17} /></button><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Northstar Energy Procurement</div><div className="mt-0.5 text-sm font-semibold">Operations workspace</div></div></div><div className="flex items-center gap-3"><StatusBadge label={mode} /><div className="hidden items-center gap-2 rounded-full border border-line bg-white px-3 py-1.5 text-xs font-medium text-slate-600 sm:flex"><span className="h-2 w-2 rounded-full bg-amber" />Wallet not connected · {LIVE_NETWORK}</div><div className="grid h-9 w-9 items-center justify-center rounded-full bg-[#d8e5dd] text-xs font-bold text-moss">NE</div></div></header><div className="px-5 py-6 lg:px-8 lg:py-8">{children}</div></main></div>;
}
