import { useState } from "react";
import { ArrowUpRight, Check, ChevronRight, FileSearch, Info, X } from "lucide-react";
import type { DemoData, EvaluationCell, Requirement } from "../types/procura";
import { Panel, PanelHeader } from "../components/Panel";
import { StatusBadge } from "../components/StatusBadge";

function Cell({ cell, onClick }: { cell: EvaluationCell; onClick: () => void }) {
  const icon = cell.status === "PASS" ? <Check size={14} /> : cell.status === "FAIL" ? <X size={14} /> : cell.status === "EQUIVALENT" ? <ArrowUpRight size={14} /> : <Info size={14} />;
  return <button onClick={onClick} className={`group flex min-h-[96px] w-full flex-col justify-between rounded-xl border p-3 text-left transition hover:-translate-y-0.5 hover:shadow-md ${cell.status === "PASS" ? "border-[#c6dfd1] bg-[#f4faf6]" : cell.status === "FAIL" ? "border-[#ecc4bf] bg-[#fff8f7]" : cell.status === "EQUIVALENT" ? "border-[#c7dae7] bg-[#f5f9fb]" : "border-line bg-[#fbfcfa]"}`}><div className="flex items-center justify-between"><span className="flex items-center gap-1.5 text-xs font-bold tracking-[.08em] text-ink">{icon}{cell.status}</span><ChevronRight size={14} className="text-slate-400 opacity-0 transition group-hover:opacity-100" /></div><span className="line-clamp-2 text-xs leading-5 text-slate-600">{cell.note}</span><span className="text-[10px] font-semibold uppercase tracking-[.1em] text-slate-400">Open evidence</span></button>;
}

function Drawer({ requirement, supplier, cell, onClose }: { requirement: Requirement; supplier: string; cell: EvaluationCell; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex justify-end bg-ink/20" role="presentation" onClick={onClose}><aside role="dialog" aria-label="Evaluation detail" onClick={(event) => event.stopPropagation()} className="h-full w-full max-w-[480px] overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Evaluation detail</div><h2 className="mt-2 text-xl font-semibold">{requirement.title}</h2><p className="mt-1 text-sm text-slate-500">{supplier}</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-paper" aria-label="Close drawer"><X size={18} /></button></div><div className="mt-6"><StatusBadge label={cell.status} /></div><div className="mt-6 space-y-5"><section><div className="label">Frozen requirement</div><p className="mt-2 text-sm leading-6 text-ink">{requirement.detail}</p></section><section><div className="label">Supplier response</div><p className="mt-2 rounded-xl bg-paper p-3 text-sm leading-6 text-slate-700">{cell.note}</p></section><section><div className="label">Evidence identity</div><div className="mt-2 flex items-start gap-3 rounded-xl border border-line p-3"><FileSearch size={17} className="mt-0.5 text-moss" /><div className="text-sm"><div className="font-medium">{cell.evidence}</div><div className="mt-1 text-xs text-slate-500">Source identity authenticated · content hash bound</div></div></div></section><section><div className="label">Objective findings</div><p className="mt-2 text-sm text-slate-700">{cell.objectiveFinding}</p></section><section><div className="label">Semantic result</div><code className="mt-2 block rounded-xl bg-[#1f2a2e] p-3 text-xs leading-6 text-[#d8e5dd]">{cell.semanticResult}</code></section><section><div className="label">Adjudication provenance</div><p className="mt-2 text-sm text-slate-700">{cell.provenance}</p></section></div></aside></div>;
}

export function EvaluationRoom({ data }: { data: DemoData }) {
  const [selected, setSelected] = useState<{ requirement: Requirement; supplier: string; cell: EvaluationCell } | null>(null);
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Flagship surface · pre-award</div><h1 className="page-title">Evaluation Room</h1><p className="page-subtitle">Compare suppliers against the frozen requirement set. The matrix is deterministic; semantic cells carry bounded adjudication provenance.</p></div><div className="flex gap-2"><button className="secondary-button"><FileSearch size={15} />View evidence register</button><button className="primary-button">Freeze evaluation</button></div></div><div className="flex flex-wrap gap-2"><StatusBadge label="CONTROLLED DEMO" /><span className="text-xs text-slate-500">{data.tender.id} · {data.tender.title}</span><span className="text-xs text-slate-400">Last readback 04 Oct 2026, 15:42 WAT</span></div><Panel><PanelHeader eyebrow="Frozen comparison · 7 requirements" title="Supplier conformity matrix" detail="Click any cell to inspect evidence, objective findings, semantic result, and provenance." action={<div className="flex gap-3 text-[11px] text-slate-500"><span><b className="text-moss">4</b> pass</span><span><b className="text-rose">1</b> fail</span><span><b className="text-amber">4</b> review</span></div>} /><div className="overflow-x-auto"><div className="min-w-[920px] p-4"><div className="grid grid-cols-[230px_repeat(3,minmax(190px,1fr))] gap-3 border-b border-line px-2 pb-3"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Frozen requirement</div>{data.suppliers.map((supplier, index) => <div key={supplier.id} className="px-1"><div className="text-sm font-semibold text-ink">{supplier.shortName}</div><div className="mt-1 flex items-center gap-2 text-[11px] text-slate-500"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-moss" : "bg-slate-300"}`} />{index === 0 ? "Recommended" : "Under review"}</div></div>)}</div><div className="space-y-3 pt-3">{data.evaluationRows.map((row) => <div key={row.requirement.id} className="grid grid-cols-[230px_repeat(3,minmax(190px,1fr))] items-stretch gap-3"><div className="rounded-xl border border-line bg-[#fbfcfa] p-3"><div className="flex items-center gap-2"><span className="text-[10px] font-bold text-slate-400">{row.requirement.id}</span>{row.requirement.mandatory && <span className="text-[9px] font-bold uppercase tracking-[.1em] text-rose">Mandatory</span>}</div><div className="mt-2 text-sm font-semibold">{row.requirement.title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{row.requirement.detail}</div></div>{data.suppliers.map((supplier) => <Cell key={supplier.id} cell={row.cells[supplier.id]} onClick={() => setSelected({ requirement: row.requirement, supplier: supplier.name, cell: row.cells[supplier.id] })} />)}</div>)}</div></div></div></Panel>{selected && <Drawer {...selected} onClose={() => setSelected(null)} />}</div>;
}
