import { ArrowRight, CircleDashed, FileCheck2, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import type { RouteKey } from "../components/Shell";
import { Panel, PanelHeader } from "../components/Panel";
import { StatusBadge } from "../components/StatusBadge";
import type { DemoData } from "../types/procura";
import { bidArgsSchema, serializeBid } from "../lib/serialization";

export function Workspace({ route, data, onNavigate }: { route: RouteKey; data: DemoData; onNavigate: (route: RouteKey) => void }) {
  const { register, handleSubmit, formState: { errors } } = useForm({ resolver: zodResolver(bidArgsSchema), defaultValues: { bidId: "BID-NEW-001", tenderId: data.tender.id, price: 420000, currency: data.tender.currency, deliveryCommitment: "30 days", requirementResponses: "Responses anchored to frozen requirement versions", submittedAt: "2026-10-05T09:00:00+01:00", bidHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" } });
  const title = route === "command-center" ? "Command Center" : route.replaceAll("-", " ").replace(/\b\w/g, (char) => char.toUpperCase());
  if (route === "bid-builder") return <div className="mx-auto max-w-3xl space-y-6"><div><div className="eyebrow">Supplier workflow</div><h1 className="page-title">Bid Builder</h1><p className="page-subtitle">Serialize a bid against the frozen tender. Evidence is attached as authenticated records, not trusted URLs.</p></div><Panel><PanelHeader eyebrow="PROCUREMENT_V1" title="Submit a bid" detail="The form schema mirrors the contract argument order." /><form onSubmit={handleSubmit((values) => { void serializeBid(values); })} className="grid gap-5 p-5 sm:grid-cols-2"><label className="field"><span>Bid ID</span><input {...register("bidId")} />{errors.bidId && <small>{errors.bidId.message as string}</small>}</label><label className="field"><span>Tender ID</span><input {...register("tenderId")} />{errors.tenderId && <small>{errors.tenderId.message as string}</small>}</label><label className="field"><span>Price</span><input type="number" {...register("price", { valueAsNumber: true })} />{errors.price && <small>{errors.price.message as string}</small>}</label><label className="field"><span>Currency</span><input {...register("currency")} /></label><label className="field sm:col-span-2"><span>Delivery commitment</span><input {...register("deliveryCommitment")} /></label><label className="field sm:col-span-2"><span>Requirement responses</span><textarea rows={4} {...register("requirementResponses")} /></label><div className="sm:col-span-2 flex items-center justify-between"><div className="text-xs text-slate-500">Hash and timestamp are validated before a broadcast can be prepared.</div><button className="primary-button" type="submit">Validate bid <ArrowRight size={15} /></button></div></form></Panel></div>;
  if (route === "command-center") return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Monday · 05 October 2026</div><h1 className="page-title">Good morning, Northstar.</h1><p className="page-subtitle">One procurement needs a decision; one delivery needs an inspection.</p></div><button onClick={() => onNavigate("tender-builder")} className="primary-button"><Plus size={15} />Create tender</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active tenders", "04", "2 due this week"], ["Awaiting evaluation", "03", "Frozen requirements"], ["In inspection", "01", "Payment blocked"], ["Escrow liability", "420,000", "USDC · controlled demo"]].map(([label, value, detail]) => <div key={label} className="rounded-2xl border border-line bg-white p-5 shadow-panel"><div className="text-xs text-slate-500">{label}</div><div className="mt-3 text-3xl font-semibold tracking-[-.05em]">{value}</div><div className="mt-2 text-xs text-slate-400">{detail}</div></div>)}</div><div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><Panel><PanelHeader eyebrow="Needs attention" title="Work queue" action={<button className="text-xs font-semibold text-moss">View all</button>} /><div className="divide-y divide-line">{[["Inspection Room", "Solar battery substitution detected", "BLOCKED", "inspection-room"], ["Evaluation Room", "Supplier comparison ready", "REVIEW", "evaluation-room"], ["Award Desk", "Supplier acceptance pending", "ACTIVE", "award-desk"]].map(([surface, item, badge, destination]) => <button key={surface} onClick={() => onNavigate(destination as RouteKey)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left hover:bg-[#fbfcfa]"><div><div className="text-sm font-semibold">{item}</div><div className="mt-1 text-xs text-slate-500">{surface}</div></div><div className="flex items-center gap-3"><StatusBadge label={badge as "BLOCKED" | "REVIEW" | "ACTIVE"} /><ArrowRight size={15} className="text-slate-400" /></div></button>)}</div></Panel><Panel><PanelHeader eyebrow="Protocol status" title="Trust boundary" /><div className="space-y-4 p-5">{[[ShieldCheck, "Deterministic state", "Hashes, amounts, deadlines"], [Sparkles, "Semantic layer", "Evidence conformity only"], [CircleDashed, "Live connection", "Not connected · review only"]].map(([Icon, label, detail]) => <div key={label as string} className="flex gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf3ef] text-moss"><Icon size={15} /></div><div><div className="text-sm font-semibold">{label as string}</div><div className="mt-0.5 text-xs text-slate-500">{detail as string}</div></div></div>)}</div></Panel></div></div>;
  return <div className="mx-auto max-w-4xl space-y-6"><div><div className="eyebrow">Procura workspace</div><h1 className="page-title">{title}</h1><p className="page-subtitle">This foundation surface is wired for the same contract and transaction architecture as the flagship rooms.</p></div><Panel><PanelHeader eyebrow="Foundation surface" title="Ready for operator review" detail="No live state is being mixed with controlled demo data." /><div className="grid gap-4 p-5 sm:grid-cols-3">{[[FileCheck2, "Frozen schema", "PROCUREMENT_V1"], [ShieldCheck, "Proof boundary", "Authenticated evidence"], [CircleDashed, "Connection", "Review only"]].map(([Icon, label, value]) => <div key={label as string} className="rounded-xl border border-line bg-[#fbfcfa] p-4"><Icon size={18} className="text-moss" /><div className="mt-4 text-sm font-semibold">{label as string}</div><div className="mt-1 text-xs text-slate-500">{value as string}</div></div>)}</div></Panel></div>;
}
